
source 'https://rubygems.org/'

gem 'rails', '3.2.15'

gem 'rest-client' # for rest-core
gem 'rest-core', :path => '../../rest-core'
gem 'rest-more', :path => '../../'

group 'test' do
  gem 'muack'
  gem 'webmock'
end

platforms(:ruby) do
  gem 'yajl-ruby'
end

platforms(:jruby) do
  gem 'jruby-openssl'
end

platforms(:rbx) do
  gem 'rubysl-test-unit'  # required by activesupport
  gem 'rubysl-enumerator' # required by activesupport
  gem 'rubysl-rexml'      # required by webmock required by crack
  gem 'racc'              # required by journey required by actionpack
end
