
source 'http://rubygems.org'

gem 'rails', '3.2.13'

gem 'rest-client' # for rest-core
gem 'rest-core', :path => '../../rest-core'
gem 'rest-more', :path => '../../'

group 'test' do
  gem 'rr'
  gem 'webmock'
end

platforms(:ruby) do
  gem 'yajl-ruby'
  gem 'psych' # why?
end

platforms(:jruby) do
  gem 'jruby-openssl'
end
